function dfdelta = dfud(z_i,h_i,delta_i,z_min,z_max,delta_min,delta_max)
%DFUD
%    DFDELTA = DFUD(Z_I,H_I,DELTA_I,Z_MIN,Z_MAX,DELTA_MIN,DELTA_MAX)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    05-Nov-2018 21:05:56

t2 = delta_i-delta_min;
t3 = delta_min-delta_max;
dfdelta = 1.0./t3.^4.*(t2.^2-t3.^2).*(delta_i.*2.0-delta_min.*2.0).*(2.0./3.0);
