function dfh = dfuh(z_i,h_i,delta_i,z_min,z_max,delta_min,delta_max)
%DFUH
%    DFH = DFUH(Z_I,H_I,DELTA_I,Z_MIN,Z_MAX,DELTA_MIN,DELTA_MAX)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    05-Nov-2018 21:05:56

t3 = pi.*(1.0./2.0);
t2 = -delta_max+t3;
dfh = h_i.*1.0./t2.^4.*(h_i.^2-t2.^2).*(4.0./3.0);
