function f = ftmp(z_i,z_min,z_max,h_i,delta_i,delta_min,delta_max)
%FTMP
%    F = FTMP(Z_I,Z_MIN,Z_MAX,H_I,DELTA_I,DELTA_MIN,DELTA_MAX)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-Sep-2018 19:50:21

t2 = tan(delta_i-h_i)-tan(delta_i+h_i);
t3 = tan(delta_max.*3.0-pi.*(1.0./2.0))+tan(delta_max-pi.*(1.0./2.0));
f = -((delta_i-delta_max).*(tanh((z_min-z_i.*sqrt(t2.^2.*(1.0./4.0)+1.0))./(z_min-z_max.*sqrt(t3.^2.*(1.0./4.0)+1.0)))-1.0))./(delta_min-delta_max);
