function f = fu(z_i,h_i,delta_i,z_min,z_max,delta_min,delta_max)
%FU
%    F = FU(Z_I,H_I,DELTA_I,Z_MIN,Z_MAX,DELTA_MIN,DELTA_MAX)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    05-Nov-2018 21:05:56

t2 = delta_i-delta_min;
t3 = delta_min-delta_max;
t4 = t2.^2-t3.^2;
t7 = pi.*(1.0./2.0);
t5 = -delta_max+t7;
t6 = h_i.^2-t5.^2;
t8 = z_i-z_min;
t9 = z_min-z_max;
t10 = t8.^2-t9.^2;
f = 1.0./t3.^4.*t4.^2.*(1.0./3.0)+1.0./t5.^4.*t6.^2.*(1.0./3.0)+1.0./t9.^4.*t10.^2.*(1.0./3.0);
