function out1 = jd(z,h,d,t,x,y,k)
%JD
%    OUT1 = JD(Z,H,D,T,X,Y,K)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    01-Sep-2018 18:36:15

t5 = d-h;
t2 = tan(t5);
t7 = d+h;
t3 = tan(t7);
t4 = cos(k);
t6 = t2.^2;
t8 = t3.^2;
t13 = t3.*(1.0./2.0);
t14 = t2.*(1.0./2.0);
t9 = -t13+t14;
t10 = tan(d);
t11 = sin(k);
t12 = sin(t);
t15 = t13-t14;
t16 = t6-t8;
t17 = t6+t8+2.0;
t18 = cos(t);
t19 = t15.^2;
t20 = t19+1.0;
t21 = t10.^2;
t22 = t21+1.0;
t23 = 1.0./sqrt(t20);
t24 = t6.*(1.0./2.0);
t25 = t8.*(1.0./2.0);
t26 = t24-t25;
out1 = [t4.*t16.*z.*(-1.0./2.0)+t4.*t17.*t18.*z.*(1.0./2.0)-t11.*t12.*t22.*z.*sqrt(t9.^2+1.0)+t10.*t11.*t12.*t15.*t23.*t26.*z;t11.*t16.*z.*(-1.0./2.0)+t4.*t12.*t17.*z.*(1.0./2.0)+t11.*t18.*sqrt(t20).*t22.*z-t10.*t11.*t15.*t18.*t23.*t26.*z];
